// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Sistema_Turnos.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbHospitales = new HashSet<tbHospitales>();
        }

        public string Ciud_Id { get; set; }
        public string Ciud_Descripcion { get; set; }
        public string Esta_Id { get; set; }
        public bool? Ciud_Estado { get; set; }
        public int Ciud_Creacion { get; set; }
        public DateTime Ciud_FechaCreacion { get; set; }
        public int? Ciud_Modificacion { get; set; }
        public DateTime? Ciud_FechaModificacion { get; set; }

        [NotMapped]
        public string usua_creac { get; set; }

        [NotMapped]
        public string usua_modi { get; set; }

        [NotMapped]
        public string Esta_Descripcion { get; set; }

        public virtual tbUsuarios Ciud_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ciud_ModificacionNavigation { get; set; }
        public virtual tbEstados Esta { get; set; }
        public virtual ICollection<tbHospitales> tbHospitales { get; set; }
    }
}