// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Turnos.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbTurnosPorEmpleados = new HashSet<tbTurnosPorEmpleados>();
        }

        public int Empl_Id { get; set; }
        public string Pers_Identidad { get; set; }
        public int? Usua_Id { get; set; }
        public int? Carg_Id { get; set; }
        public int? Hosp_Id { get; set; }
        public bool? Empl_Estado { get; set; }
        public int Empl_Creacion { get; set; }
        public DateTime Empl_FechaCreacion { get; set; }
        public int? Empl_Modificacion { get; set; }
        public DateTime? Empl_FechaModificacion { get; set; }

        public virtual tbCargos Carg { get; set; }
        public virtual tbUsuarios Empl_CreacionNavigation { get; set; }
        public virtual tbUsuarios Empl_ModificacionNavigation { get; set; }
        public virtual tbHospitales Hosp { get; set; }
        public virtual tbPersonas Pers_IdentidadNavigation { get; set; }
        public virtual ICollection<tbTurnosPorEmpleados> tbTurnosPorEmpleados { get; set; }
    }
}