// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Sistema_Turnos.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int Carg_Id { get; set; }
        public string Carg_Descripcion { get; set; }
        public bool? Carg_Estado { get; set; }
        public int Carg_Creacion { get; set; }
        public DateTime Carg_FechaCreacion { get; set; }
        public int? Carg_Modificacion { get; set; }
        public DateTime? Carg_FechaModificacion { get; set; }

        public virtual tbUsuarios Carg_CreacionNavigation { get; set; }
        public virtual tbUsuarios Carg_ModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}