// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Sistema_Turnos.Entities.Entities;

#nullable disable

namespace Sistema_Turnos.DataAccess.Context
{
    public partial class BaseturnosContext : DbContext
    {
        public BaseturnosContext()
        {
        }

        public BaseturnosContext(DbContextOptions<BaseturnosContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbEmpleados> tbEmpleados { get; set; }
        public virtual DbSet<tbEstados> tbEstados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbHospitales> tbHospitales { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbTurnos> tbTurnos { get; set; }
        public virtual DbSet<tbTurnosPorEmpleados> tbTurnosPorEmpleados { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.Carg_Id)
                    .HasName("PK__tbCargos__B0D859FA7214D662");

                entity.ToTable("tbCargos", "Gene");

                entity.Property(e => e.Carg_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Carg_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Carg_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Carg_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Carg_CreacionNavigation)
                    .WithMany(p => p.tbCargosCarg_CreacionNavigation)
                    .HasForeignKey(d => d.Carg_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbCargos__Carg_C__628FA481");

                entity.HasOne(d => d.Carg_ModificacionNavigation)
                    .WithMany(p => p.tbCargosCarg_ModificacionNavigation)
                    .HasForeignKey(d => d.Carg_Modificacion)
                    .HasConstraintName("FK__tbCargos__Carg_M__6383C8BA");
            });

            modelBuilder.Entity<tbCiudades>(entity =>
            {
                entity.HasKey(e => e.Ciud_Id)
                    .HasName("PK__tbCiudad__D04530886645BE01");

                entity.ToTable("tbCiudades", "Gene");

                entity.Property(e => e.Ciud_Id)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Ciud_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Ciud_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Ciud_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Ciud_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Esta_Id)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.HasOne(d => d.Ciud_CreacionNavigation)
                    .WithMany(p => p.tbCiudadesCiud_CreacionNavigation)
                    .HasForeignKey(d => d.Ciud_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbCiudade__Ciud___5AEE82B9");

                entity.HasOne(d => d.Ciud_ModificacionNavigation)
                    .WithMany(p => p.tbCiudadesCiud_ModificacionNavigation)
                    .HasForeignKey(d => d.Ciud_Modificacion)
                    .HasConstraintName("FK__tbCiudade__Ciud___5BE2A6F2");

                entity.HasOne(d => d.Esta)
                    .WithMany(p => p.tbCiudades)
                    .HasForeignKey(d => d.Esta_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbCiudade__Esta___4F7CD00D");
            });

            modelBuilder.Entity<tbEmpleados>(entity =>
            {
                entity.HasKey(e => e.Empl_Id)
                    .HasName("PK__tbEmplea__2EB12E866520A9C2");

                entity.ToTable("tbEmpleados", "Turn");

                entity.Property(e => e.Empl_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Empl_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Empl_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_Identidad)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.HasOne(d => d.Carg)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Carg_Id)
                    .HasConstraintName("FK__tbEmplead__Carg___52593CB8");

                entity.HasOne(d => d.Empl_CreacionNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_CreacionNavigation)
                    .HasForeignKey(d => d.Empl_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbEmplead__Empl___6477ECF3");

                entity.HasOne(d => d.Empl_ModificacionNavigation)
                    .WithMany(p => p.tbEmpleadosEmpl_ModificacionNavigation)
                    .HasForeignKey(d => d.Empl_Modificacion)
                    .HasConstraintName("FK__tbEmplead__Empl___656C112C");

                entity.HasOne(d => d.Hosp)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Hosp_Id)
                    .HasConstraintName("FK__tbEmplead__Hosp___534D60F1");

                entity.HasOne(d => d.Pers_IdentidadNavigation)
                    .WithMany(p => p.tbEmpleados)
                    .HasForeignKey(d => d.Pers_Identidad)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbEmplead__Pers___5441852A");
            });

            modelBuilder.Entity<tbEstados>(entity =>
            {
                entity.HasKey(e => e.Esta_Id)
                    .HasName("PK__tbEstado__D52AE7B8722FA192");

                entity.ToTable("tbEstados", "Gene");

                entity.Property(e => e.Esta_Id)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Esta_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Esta_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Esta_CreacionNavigation)
                    .WithMany(p => p.tbEstadosEsta_CreacionNavigation)
                    .HasForeignKey(d => d.Esta_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbEstados__Esta___59063A47");

                entity.HasOne(d => d.Esta_ModificacionNavigation)
                    .WithMany(p => p.tbEstadosEsta_ModificacionNavigation)
                    .HasForeignKey(d => d.Esta_Modificacion)
                    .HasConstraintName("FK__tbEstados__Esta___59FA5E80");
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.EsCi_Id)
                    .HasName("PK__tbEstado__6D720574353EA5C1");

                entity.ToTable("tbEstadosCiviles", "Gene");

                entity.Property(e => e.EsCi_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EsCi_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.EsCi_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.EsCi_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.EsCi_CreacionNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsCi_CreacionNavigation)
                    .HasForeignKey(d => d.EsCi_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbEstados__EsCi___60A75C0F");

                entity.HasOne(d => d.EsCi_ModificacionNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsCi_ModificacionNavigation)
                    .HasForeignKey(d => d.EsCi_Modificacion)
                    .HasConstraintName("FK__tbEstados__EsCi___619B8048");
            });

            modelBuilder.Entity<tbHospitales>(entity =>
            {
                entity.HasKey(e => e.Hosp_Id)
                    .HasName("PK__tbHospit__347D3790DB320131");

                entity.ToTable("tbHospitales", "Turn");

                entity.Property(e => e.Ciud_Id)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Hosp_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Hosp_Direccion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Hosp_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Hosp_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Hosp_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Ciud)
                    .WithMany(p => p.tbHospitales)
                    .HasForeignKey(d => d.Ciud_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbHospita__Ciud___5070F446");

                entity.HasOne(d => d.Hosp_CreacionNavigation)
                    .WithMany(p => p.tbHospitalesHosp_CreacionNavigation)
                    .HasForeignKey(d => d.Hosp_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbHospita__Hosp___5CD6CB2B");

                entity.HasOne(d => d.Hosp_ModificacionNavigation)
                    .WithMany(p => p.tbHospitalesHosp_ModificacionNavigation)
                    .HasForeignKey(d => d.Hosp_Modificacion)
                    .HasConstraintName("FK__tbHospita__Hosp___5DCAEF64");
            });

            modelBuilder.Entity<tbPantallas>(entity =>
            {
                entity.HasKey(e => e.Pant_Id)
                    .HasName("PK__tbPantal__CF98C9322472C5A9");

                entity.ToTable("tbPantallas", "Acce");

                entity.Property(e => e.Pant_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pant_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Pant_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pant_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Pant_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPant_CreacionNavigation)
                    .HasForeignKey(d => d.Pant_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPantall__Pant___49C3F6B7");

                entity.HasOne(d => d.Pant_ModificacionNavigation)
                    .WithMany(p => p.tbPantallasPant_ModificacionNavigation)
                    .HasForeignKey(d => d.Pant_Modificacion)
                    .HasConstraintName("FK__tbPantall__Pant___4AB81AF0");
            });

            modelBuilder.Entity<tbPantallasPorRoles>(entity =>
            {
                entity.HasKey(e => e.PaRo_Id)
                    .HasName("PK__tbPantal__22884657465BC2AB");

                entity.ToTable("tbPantallasPorRoles", "Acce");

                entity.Property(e => e.PaRo_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.PaRo_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.PaRo_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.PaRo_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPorRolesPaRo_CreacionNavigation)
                    .HasForeignKey(d => d.PaRo_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPantall__PaRo___4D94879B");

                entity.HasOne(d => d.PaRo_ModificacionNavigation)
                    .WithMany(p => p.tbPantallasPorRolesPaRo_ModificacionNavigation)
                    .HasForeignKey(d => d.PaRo_Modificacion)
                    .HasConstraintName("FK__tbPantall__PaRo___4E88ABD4");

                entity.HasOne(d => d.Pant)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Pant_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPantall__Pant___4CA06362");

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Rol_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPantall__Rol_I__4BAC3F29");
            });

            modelBuilder.Entity<tbPersonas>(entity =>
            {
                entity.HasKey(e => e.Pers_Identidad)
                    .HasName("PK__tbPerson__AD2773985F47D5A3");

                entity.ToTable("tbPersonas", "Gene");

                entity.Property(e => e.Pers_Identidad)
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Pers_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_PrimerApellido)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_PrimerNombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_SegundoApellido)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_SegundoNombre)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Sexo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.EsCi)
                    .WithMany(p => p.tbPersonas)
                    .HasForeignKey(d => d.EsCi_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPersona__EsCi___5165187F");

                entity.HasOne(d => d.Pers_CreacionNavigation)
                    .WithMany(p => p.tbPersonasPers_CreacionNavigation)
                    .HasForeignKey(d => d.Pers_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbPersona__Pers___5EBF139D");

                entity.HasOne(d => d.Pers_ModificacionNavigation)
                    .WithMany(p => p.tbPersonasPers_ModificacionNavigation)
                    .HasForeignKey(d => d.Pers_Modificacion)
                    .HasConstraintName("FK__tbPersona__Pers___5FB337D6");
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Rol_Id)
                    .HasName("PK__tbRoles__795EBD494E42B491");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.Rol_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Rol_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Rol_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Rol_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Rol_CreacionNavigation)
                    .WithMany(p => p.tbRolesRol_CreacionNavigation)
                    .HasForeignKey(d => d.Rol_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbRoles__Rol_Cre__47DBAE45");

                entity.HasOne(d => d.Rol_ModificacionNavigation)
                    .WithMany(p => p.tbRolesRol_ModificacionNavigation)
                    .HasForeignKey(d => d.Rol_Modificacion)
                    .HasConstraintName("FK__tbRoles__Rol_Mod__48CFD27E");
            });

            modelBuilder.Entity<tbTurnos>(entity =>
            {
                entity.HasKey(e => e.Turn_Id)
                    .HasName("PK__tbTurnos__8101702B325113E8");

                entity.ToTable("tbTurnos", "Turn");

                entity.Property(e => e.Turn_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Turn_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Turn_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Turn_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Turn_CreacionNavigation)
                    .WithMany(p => p.tbTurnosTurn_CreacionNavigation)
                    .HasForeignKey(d => d.Turn_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbTurnos__Turn_C__66603565");

                entity.HasOne(d => d.Turn_ModificacionNavigation)
                    .WithMany(p => p.tbTurnosTurn_ModificacionNavigation)
                    .HasForeignKey(d => d.Turn_Modificacion)
                    .HasConstraintName("FK__tbTurnos__Turn_M__6754599E");
            });

            modelBuilder.Entity<tbTurnosPorEmpleados>(entity =>
            {
                entity.HasKey(e => e.TuEm_Id)
                    .HasName("PK__tbTurnos__90F635CC8CF768D5");

                entity.ToTable("tbTurnosPorEmpleados", "Turn");

                entity.Property(e => e.TuEm_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.TuEm_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.TuEm_FechaInicio).HasColumnType("date");

                entity.Property(e => e.TuEm_FechaModificacion).HasColumnType("datetime");

                entity.HasOne(d => d.Empl)
                    .WithMany(p => p.tbTurnosPorEmpleados)
                    .HasForeignKey(d => d.Empl_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbTurnosP__Empl___5629CD9C");

                entity.HasOne(d => d.TuEm_CreacionNavigation)
                    .WithMany(p => p.tbTurnosPorEmpleadosTuEm_CreacionNavigation)
                    .HasForeignKey(d => d.TuEm_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbTurnosP__TuEm___68487DD7");

                entity.HasOne(d => d.TuEm_ModificacionNavigation)
                    .WithMany(p => p.tbTurnosPorEmpleadosTuEm_ModificacionNavigation)
                    .HasForeignKey(d => d.TuEm_Modificacion)
                    .HasConstraintName("FK__tbTurnosP__TuEm___693CA210");

                entity.HasOne(d => d.Turn)
                    .WithMany(p => p.tbTurnosPorEmpleados)
                    .HasForeignKey(d => d.Turn_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbTurnosP__Turn___5535A963");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EE669C5D8C");

                entity.ToTable("tbUsuarios", "Acce");

                entity.Property(e => e.Usua_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Usua_FechaCreacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_FechaModificacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_Usuario)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Usua_CreacionNavigation)
                    .WithMany(p => p.InverseUsua_CreacionNavigation)
                    .HasForeignKey(d => d.Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbUsuario__Usua___571DF1D5");

                entity.HasOne(d => d.Usua_ModificacionNavigation)
                    .WithMany(p => p.InverseUsua_ModificacionNavigation)
                    .HasForeignKey(d => d.Usua_Modificacion)
                    .HasConstraintName("FK__tbUsuario__Usua___5812160E");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}